const data = [
  {
    id: 1,
    btn: "Experince Sharing",
    date: "November 16, 2023",
    user: "Infonits22",
    heading:
      "infonits Shuttle Clash Event Showcases IT Excellence in Northern Province",
    image: "../blogAssets/blogimg19.webp",
  },
  {
    id: 2,
    btn: "Experience Sharing",
    date: "April 28, 2023",
    user: "Infonits22",
    heading: "Top 10 Essential skills for successful web designers",
    image: "../blogAssets/blogimg18.webp",
  },
  {
    id: 3,
    btn: "Experince Sharing",
    date: "April 7, 2023",
    user: "Infonits22",
    heading: "Best 5 WooCommerce Plugins To Boost Conversions and Sales",
    image: "../blogAssets/blogimg17.webp",
  },
  {
    id: 4,
    btn: "Experince Sharing",
    date: "September 4, 2022",
    user: "Infonits22",
    heading: "Sharing our experience with students",
    image: "../blogAssets/blogimg16.webp",
  },
  {
    id: 5,
    btn: "Experince Sharing",
    date: "April 21, 2023",
    user: "Infonits22",
    heading: "The Future of Front-End Development Trends to Watch in 2023",
    image: "../blogAssets/blogimg15.webp",
  },
  {
    id: 6,
    btn: "Experince Sharing",
    date: "September 4, 2022",
    user: "Infonits22",
    heading: "A Good Starting to Educate School Students",
    image: "../blogAssets/blogimg14.webp",
  },
  {
    id: 7,
    btn: "Experince Sharing",
    date: "April 1, 2023",
    user: "Infonits22",
    heading: "Social Media Strategies for Online Businesses",
    image: "../blogAssets/blogimg13.webp",
  },
  {
    id: 8,
    btn: "Experince Sharing",
    date: "April 28, 2023",
    user: "Infonits22",
    heading: "Avoid the Common Web Design Mistakes",
    image: "../blogAssets/blogimg12.webp",
  },
  {
    id: 9,
    btn: "Experince Sharing",
    date: "May 12, 2023",
    user: "Infonits22",
    heading: "Why Should You Update Your Website Reqularly",
    image: "../blogAssets/blogimg11.webp",
  },
  {
    id: 10,
    btn: "Experince Sharing",
    date: "July 28, 2023",
    user: "Infonits22",
    heading: "The Future of E-Commerce in Sri Lanka",
    image: "../blogAssets/blogimg10.webp",
  },
  {
    id: 11,
    btn: "Experince Sharing",
    date: "April 10, 2023",
    user: "Infonits22",
    heading: "WordPress Perfomance Optimization Tips",
    image: "../blogAssets/blogimg9.webp",
  },
  {
    id: 12,
    btn: "Experince Sharing",
    date: "June 3, 2023",
    user: "Infonits22",
    heading: "10 Powerful Ways to Use Google Trends for SEO",
    image: "../blogAssets/blogimg8.webp",
  },
  {
    id: 13,
    btn: "Experince Sharing",
    date: "June 19, 2023",
    user: "Infonits22",
    heading: "10 Secrets of Succesful Video Marketing",
    image: "../blogAssets/blogimg7.webp",
  },
  {
    id: 14,
    btn: "Experince Sharing",
    date: "March 11, 2023",
    user: "Infonits22",
    heading: "Visual Design's Building Blocks",
    image: "../blogAssets/blogimg6.webp",
  },
  {
    id: 15,
    btn: "Sponsor",
    date: "November 12, 2022",
    user: "Infonits22",
    heading: "Hackforce22 as a Gold Sponsor",
    image: "../blogAssets/blogimg5.webp",
  },
  {
    id: 16,
    btn: "Infonits Update",
    date: "October 18, 2022",
    user: "Infonits22",
    heading: "We are Thrilled to Announce",
    image: "../blogAssets/blogimg4.webp",
  },
  {
    id: 17,
    btn: "Experince Sharing",
    date: "July 15, 2023",
    user: "Infonits22",
    heading: "Why Responsive Web Design is a Must in 2023",
    image: "../blogAssets/blogimg3.webp",
  },
  {
    id: 18,
    btn: "Parnership",
    date: "September 4, 2022",
    user: "Infonits22",
    heading: "Hackforce21 as a Technology Partner",
    image: "../blogAssets/blogimg2.webp",
  },
  {
    id: 19,
    btn: "Experince Sharing",
    date: "August 5, 2023",
    user: "Infonits22",
    heading: "10 Website Accessibility Best Practices to Improve UX",
    image: "../blogAssets/blogimg1.webp",
  },
];
export default data;
